// Product catalog — SUITUP SOLUTIONS LIMITED
// Turkish-imported formal wear · Arcades Mall & Mosi oa Tunya Mall, Lusaka

export interface Product {
  id: string;
  name: string;
  cat: "suits" | "shirts" | "ties" | "shoes";
  subtitle: string;
  price: number; // ZMW
  fabric: string;
  color: string;
  swatch: [string, string];
  hueA: string;
  hueB: string;
  lA: number;
  lB: number;
  description: string;
  fit: string;
  origin: string;
  images?: string[]; // public/ paths, index 0 = hero, 1–3 = gallery
}

export const CATALOG: Product[] = [
  // ─── Suits ─────────────────────────────────────────────────────────────
  {
    id: "su-navy-contrast",
    name: "The Lusaka",
    cat: "suits",
    subtitle: "Navy Three-Piece, Contrast Waistcoat",
    price: 8999,
    fabric: "Premium poly-blend",
    color: "Navy",
    swatch: ["#1a2540", "#0f1826"],
    hueA: "225 8%",
    hueB: "225 6%",
    lA: 76,
    lB: 50,
    description:
      "The standout in the range. Midnight navy jacket and trousers paired with a contrasting light grey waistcoat — a combination that draws the eye without announcing itself. Single-button notch lapel, slim Italian cut.",
    fit: "Slim fit · Jacket, waistcoat & trousers",
    origin: "Imported from Turkey",
    images: [
      "/suit-img/s1-a.jpg",
      "/suit-img/s1-b.jpg",
      "/suit-img/s1-c.jpg",
      "/suit-img/s1-d.jpg",
    ],
  },
  {
    id: "su-mauve",
    name: "The Kafue",
    cat: "suits",
    subtitle: "Mauve Three-Piece",
    price: 6999,
    fabric: "Textured poly-blend",
    color: "Mauve",
    swatch: ["#7a4a50", "#5e3338"],
    hueA: "355 14%",
    hueB: "355 12%",
    lA: 78,
    lB: 54,
    description:
      "A contemporary mauve in a textured poly-blend — confident enough to be noticed, measured enough to stay in rotation. Three-piece with a notch lapel and flap pockets.",
    fit: "Slim fit · Jacket, waistcoat & trousers",
    origin: "Imported from Turkey",
    images: [
      "/suit-img/s2-a.jpg",
      "/suit-img/s2-b.jpg",
      "/suit-img/s2-c.jpg",
      "/suit-img/s2-d.jpg",
    ],
  },
  {
    id: "su-grey-db",
    name: "The Livingstone",
    cat: "suits",
    subtitle: "Light Grey Double-Breasted",
    price: 7499,
    fabric: "Premium poly-blend",
    color: "Light Grey",
    swatch: ["#b0b0b8", "#8a8a94"],
    hueA: "240 3%",
    hueB: "240 2%",
    lA: 88,
    lB: 70,
    description:
      "A six-button double-breasted in light grey — the suit that earns the second look. Peak lapels, a lean silhouette, clean trouser break. Available in both stores.",
    fit: "Slim fit · Jacket & trousers",
    origin: "Available in-store, Lusaka",
    images: [
      "/suit-img/s3-a.jpg",
      "/suit-img/s3-b.jpg",
      "/suit-img/s3-c.jpg",
      "/suit-img/s3-d.jpg",
    ],
  },
  {
    id: "su-navy-db",
    name: "The Ndola",
    cat: "suits",
    subtitle: "Navy Double-Breasted",
    price: 7999,
    fabric: "Premium poly-blend",
    color: "Navy",
    swatch: ["#1a2238", "#11182a"],
    hueA: "230 8%",
    hueB: "230 6%",
    lA: 76,
    lB: 52,
    description:
      "A six-button double-breasted in deep navy. Gunmetal buttons, peak lapels, and a clean back vent. Serious when it needs to be, effortless the rest of the time.",
    fit: "Slim fit · Jacket & trousers",
    origin: "Imported from Turkey",
    images: [
      "/suit-img/s4-a.jpg",
      "/suit-img/s4-b.jpg",
      "/suit-img/s4-c.jpg",
      "/suit-img/s4-d.jpg",
    ],
  },
  {
    id: "su-grey-vest",
    name: "The Victoria",
    cat: "suits",
    subtitle: "Light Grey Three-Piece",
    price: 6999,
    fabric: "Textured poly-blend",
    color: "Light Grey",
    swatch: ["#c0c0c8", "#9a9aa4"],
    hueA: "240 2%",
    hueB: "240 2%",
    lA: 90,
    lB: 72,
    description:
      "Light grey, three pieces, double-breasted waistcoat. A complete look that works from the Arcades to the boardroom without negotiation. Suit Up's most-restocked colour.",
    fit: "Slim fit · Jacket, waistcoat & trousers",
    origin: "Imported from Turkey",
    images: [
      "/suit-img/s5-a.jpg",
      "/suit-img/s5-b.jpg",
      "/suit-img/s5-c.jpg",
      "/suit-img/s5-d.jpg",
    ],
  },
  {
    id: "su-stone",
    name: "The Mosi",
    cat: "suits",
    subtitle: "Stone Three-Piece",
    price: 6499,
    fabric: "Woven poly-blend",
    color: "Stone",
    swatch: ["#d8d0c0", "#bfb7a4"],
    hueA: "40 6%",
    hueB: "40 4%",
    lA: 92,
    lB: 78,
    description:
      "Stone — not white, not cream, not beige. A warm neutral three-piece that photographs exceptionally well. Notch lapel, matching waistcoat, flat-front trousers.",
    fit: "Slim fit · Jacket, waistcoat & trousers",
    origin: "Imported from Turkey",
    images: [
      "/suit-img/s6-a.jpg",
      "/suit-img/s6-b.jpg",
      "/suit-img/s6-c.jpg",
      "/suit-img/s6-d.jpg",
    ],
  },
  {
    id: "su-charcoal-stripe",
    name: "The Copperbelt",
    cat: "suits",
    subtitle: "Charcoal Pinstripe Double-Breasted",
    price: 8499,
    fabric: "Pinstripe poly-blend",
    color: "Charcoal",
    swatch: ["#4a4a52", "#323238"],
    hueA: "240 4%",
    hueB: "240 3%",
    lA: 74,
    lB: 52,
    description:
      "Charcoal with a chalk pinstripe — old authority, modern cut. Double-breasted notch lapels, side vents, a slim leg. The suit for someone who has made their decision.",
    fit: "Slim fit · Jacket & trousers",
    origin: "Available in-store, Lusaka",
    images: [
      "/suit-img/s7-a.jpg",
      "/suit-img/s7-b.jpg",
      "/suit-img/s7-c.jpg",
      "/suit-img/s7-d.jpg",
    ],
  },
  {
    id: "su-grey-classic",
    name: "The Arcades",
    cat: "suits",
    subtitle: "Light Grey Classic Three-Piece",
    price: 5999,
    fabric: "Premium poly-blend",
    color: "Light Grey",
    swatch: ["#c4c4cc", "#9e9ea8"],
    hueA: "240 3%",
    hueB: "240 2%",
    lA: 88,
    lB: 68,
    description:
      "The go-to. Light grey, three-piece, notch lapel — the suit you reach for on a Thursday morning without deliberation. Suit Up's most consistently popular offering.",
    fit: "Slim fit · Jacket, waistcoat & trousers",
    origin: "Imported from Turkey",
    images: [
      "/suit-img/s8-a.jpg",
      "/suit-img/s8-b.jpg",
      "/suit-img/s8-c.jpg",
      "/suit-img/s8-d.jpg",
    ],
  },
  {
    id: "su-ivory",
    name: "The Barotse",
    cat: "suits",
    subtitle: "Ivory Three-Piece",
    price: 7499,
    fabric: "Smooth poly-blend",
    color: "Ivory",
    swatch: ["#f0ebe0", "#e0d8c8"],
    hueA: "40 8%",
    hueB: "40 6%",
    lA: 96,
    lB: 84,
    description:
      "Ivory — for a wedding, a function, or a Friday when everything else is a grey day. Six-button waistcoat, notch lapel jacket, flat-front trousers. A complete statement.",
    fit: "Slim fit · Jacket, waistcoat & trousers",
    origin: "Imported from Turkey",
    images: [
      "/suit-img/s9-a.jpg",
      "/suit-img/s9-b.jpg",
      "/suit-img/s9-c.jpg",
      "/suit-img/s9-d.jpg",
    ],
  },
  {
    id: "su-charcoal",
    name: "The Executive",
    cat: "suits",
    subtitle: "Charcoal Three-Piece",
    price: 6499,
    fabric: "Premium poly-blend",
    color: "Charcoal",
    swatch: ["#585860", "#3c3c44"],
    hueA: "240 4%",
    hueB: "240 3%",
    lA: 76,
    lB: 54,
    description:
      "Medium charcoal, three pieces. The suit that covers every occasion without specialising in any. A notch lapel, clean chest pocket, and a waistcoat that finishes the picture.",
    fit: "Slim fit · Jacket, waistcoat & trousers",
    origin: "Available in-store, Lusaka",
    images: [
      "/suit-img/s10-a.jpg",
      "/suit-img/s10-b.jpg",
      "/suit-img/s10-c.jpg",
      "/suit-img/s10-d.jpg",
    ],
  },
  {
    id: "su-navy-stripe",
    name: "The Parliament",
    cat: "suits",
    subtitle: "Navy Chalk Stripe Three-Piece",
    price: 8499,
    fabric: "Chalk stripe poly-blend",
    color: "Navy",
    swatch: ["#1e2840", "#131a2a"],
    hueA: "228 10%",
    hueB: "228 8%",
    lA: 74,
    lB: 50,
    description:
      "Deep navy with a fine chalk stripe — three-piece, peak lapel, the kind of suit that confirms an appointment before the handshake. Sharp. Unambiguous.",
    fit: "Slim fit · Jacket, waistcoat & trousers",
    origin: "Imported from Turkey",
    images: [
      "/suit-img/s11-a.jpg",
      "/suit-img/s11-b.jpg",
      "/suit-img/s11-c.jpg",
      "/suit-img/s11-d.jpg",
    ],
  },

  // ─── Shirts ────────────────────────────────────────────────────────────
  {
    id: "su-shirt-white",
    name: "White Dress Shirt",
    cat: "shirts",
    subtitle: "Slim Fit · Contrast Buttons",
    price: 1299,
    fabric: "Cotton blend",
    color: "White",
    swatch: ["#f2f0ec", "#dcdad4"],
    hueA: "40 4%",
    hueB: "40 3%",
    lA: 96,
    lB: 84,
    description:
      "A clean white dress shirt with subtle dark contrast buttons — the small detail that lifts the whole look. Slim fit, spread collar, sits cleanly under any suit in the range.",
    fit: "Slim fit",
    origin: "Imported",
    images: [
      "/images/suits/men-shirt-5a.jpg",
      "/images/suits/men-shirt-5b.jpg",
      "/images/suits/men-shirt-5c.jpg",
      "/images/suits/men-shirt-5d.jpg",
    ],
  },
  {
    id: "su-shirt-charcoal",
    name: "Charcoal Dress Shirt",
    cat: "shirts",
    subtitle: "Slim Fit · Spread Collar",
    price: 1299,
    fabric: "Stretch cotton blend",
    color: "Charcoal",
    swatch: ["#484848", "#2e2e2e"],
    hueA: "0 0%",
    hueB: "0 0%",
    lA: 72,
    lB: 50,
    description:
      "A deep charcoal dress shirt in a stretch-cotton blend — polished enough for the boardroom, versatile enough to wear out. The best pairing for the ivory and stone suits.",
    fit: "Slim fit",
    origin: "Imported",
    images: [
      "/images/suits/men-shirt-4a.jpg",
      "/images/suits/men-shirt-4b.jpg",
      "/images/suits/men-shirt-4c.jpg",
      "/images/suits/men-shirt-4d.jpg",
    ],
  },
  {
    id: "su-shirt-green",
    name: "Forest Green Shirt",
    cat: "shirts",
    subtitle: "Slim Fit · Spread Collar",
    price: 1299,
    fabric: "Cotton blend",
    color: "Forest Green",
    swatch: ["#2a5a48", "#1a3c30"],
    hueA: "158 14%",
    hueB: "158 12%",
    lA: 72,
    lB: 50,
    description:
      "A rich forest green that works surprisingly well under the grey and charcoal suits — bold enough to be noticed, considered enough to stay in rotation.",
    fit: "Slim fit",
    origin: "Imported",
    images: [
      "/images/suits/men-shirt-3a.jpg",
      "/images/suits/men-shirt-3b.jpg",
      "/images/suits/men-shirt-3c.jpg",
    ],
  },
  {
    id: "su-shirt-lavender",
    name: "Lavender Shirt",
    cat: "shirts",
    subtitle: "Slim Fit · Spread Collar",
    price: 1299,
    fabric: "Cotton blend",
    color: "Lavender",
    swatch: ["#b0a0d0", "#907aac"],
    hueA: "270 14%",
    hueB: "270 12%",
    lA: 82,
    lB: 66,
    description:
      "A soft lavender that pairs beautifully with the navy and charcoal suits — a fresh alternative to the usual white or blue. Smart, relaxed, and easy to wear.",
    fit: "Slim fit",
    origin: "Imported",
    images: [
      "/images/suits/men-shirt-2a.jpg",
      "/images/suits/men-shirt-2b.jpg",
      "/images/suits/men-shirt-2c.jpg",
      "/images/suits/men-shirt-2d.jpg",
    ],
  },
  {
    id: "su-shirt-brown",
    name: "Brown Textured Shirt",
    cat: "shirts",
    subtitle: "Regular Fit · Textured Weave",
    price: 1299,
    fabric: "Textured cotton blend",
    color: "Brown",
    swatch: ["#7a4a28", "#5a3318"],
    hueA: "25 18%",
    hueB: "25 14%",
    lA: 74,
    lB: 54,
    description:
      "A warm brown in a subtly textured weave — earthy, distinctive, and a natural match for the stone and ivory suits. The shirt for someone who doesn't need to follow the brief.",
    fit: "Regular fit",
    origin: "Imported",
    images: [
      "/images/suits/men-shirt-1a.jpg",
      "/images/suits/men-shirt-1b.jpg",
      "/images/suits/men-shirt-1c.jpg",
      "/images/suits/men-shirt-1d.jpg",
    ],
  },

  // ─── Accessories ───────────────────────────────────────────────────────
  {
    id: "su-tie-slate",
    name: "Slate Blue Tie",
    cat: "ties",
    subtitle: "Woven Silk-Feel",
    price: 799,
    fabric: "Polyester satin",
    color: "Slate Blue",
    swatch: ["#8090a8", "#606e84"],
    hueA: "215 10%",
    hueB: "215 8%",
    lA: 80,
    lB: 62,
    description:
      "A muted slate blue — sits beautifully against the grey suits and ivory, and softens the stronger navy pieces. The most versatile tie in the range.",
    fit: "7cm blade · Standard length",
    origin: "Imported",
    images: ["/images/suits/tie-1.jpg"],
  },
  {
    id: "su-tie-navy",
    name: "Navy Tie",
    cat: "ties",
    subtitle: "Woven Silk-Feel",
    price: 799,
    fabric: "Polyester satin",
    color: "Navy",
    swatch: ["#1d2a44", "#121b2e"],
    hueA: "225 12%",
    hueB: "225 10%",
    lA: 74,
    lB: 52,
    description:
      "A deep navy woven tie — simple, correct, always appropriate. Pairs with the grey suits and the stone for a controlled, well-considered look.",
    fit: "7cm blade · Standard length",
    origin: "Imported",
    images: ["/images/suits/tie-2.jpg"],
  },
  {
    id: "su-tie-cream",
    name: "Cream Tie",
    cat: "ties",
    subtitle: "Woven Silk-Feel",
    price: 799,
    fabric: "Polyester satin",
    color: "Cream",
    swatch: ["#ede5d4", "#d8cebb"],
    hueA: "38 8%",
    hueB: "38 6%",
    lA: 94,
    lB: 82,
    description:
      "A warm cream tie — the natural companion to the ivory and stone suits, and a clean contrast against navy or charcoal. Understated and intentional.",
    fit: "7cm blade · Standard length",
    origin: "Imported",
    images: ["/images/suits/tie-3.jpg"],
  },

  // ─── Shoes ─────────────────────────────────────────────────────────────
  {
    id: "su-shoe-black",
    name: "Black Oxford",
    cat: "shoes",
    subtitle: "High-Gloss Lace-Up",
    price: 2499,
    fabric: "Synthetic patent leather",
    color: "Black",
    swatch: ["#1a1a1a", "#0a0a0a"],
    hueA: "0 0%",
    hueB: "0 0%",
    lA: 60,
    lB: 36,
    description:
      "A clean, high-gloss black Oxford — the shoe that finishes any of the suits without asking for attention. Lace-up, low block heel, slim toe. Dress it up or down.",
    fit: "EU 39 – 45",
    origin: "Imported",
    images: [
      "/images/suits/shoe-1a.jpg",
      "/images/suits/shoe-1b.jpg",
      "/images/suits/shoe-1c.jpg",
      "/images/suits/shoe-1d.jpg",
    ],
  },
  {
    id: "su-shoe-brown",
    name: "Dark Brown Oxford",
    cat: "shoes",
    subtitle: "Cap-Toe · Matte Leather",
    price: 2499,
    fabric: "Synthetic leather",
    color: "Dark Brown",
    swatch: ["#3d2314", "#27160c"],
    hueA: "22 16%",
    hueB: "22 12%",
    lA: 68,
    lB: 46,
    description:
      "A dark brown cap-toe Oxford in a matte finish — the warmer alternative to black. Works best with the stone, ivory, and charcoal suits. Brown sole, contrast stitching detail.",
    fit: "EU 39 – 45",
    origin: "Imported",
    images: [
      "/images/suits/shoe-2a.jpg",
      "/images/suits/shoe-2b.jpg",
      "/images/suits/shoe-2c.jpg",
      "/images/suits/shoe-2d.jpg",
    ],
  },
];

export const SIZES: Record<string, string[]> = {
  suits: ["44", "46", "48", "50", "52", "54", "56", "58"],
  shirts: ["S", "M", "L", "XL", "XXL"],
  ties: ["One Size"],
  shoes: ["39", "40", "41", "42", "43", "44", "45"],
};

export const CATEGORIES = [
  { id: "all",    label: "All" },
  { id: "suits",  label: "Suits" },
  { id: "shirts", label: "Shirts" },
  { id: "ties",   label: "Accessories" },
  { id: "shoes",  label: "Shoes" },
] as const;

/** Format as Zambian Kwacha */
export const fmt = (n: number) =>
  "K" + Math.round(n).toLocaleString("en-ZM");
